### ISSUE TITLE
User Experience Must Have 1

### ISSUE THREAD

**Issue by Bebolor** [WomenPlusPlus/deploy-impact-21-kona-c#98] opened 2021-11-03 20:51 UTC
1. Targeted simple questions to guide users to be matched (SDGs and location) to the right help by associations.

**Comment by ClaudiaNicolae** [comment] 2021-11-05 15:30
I think this a duplicate of the current stories that we have in the Sprint. This will be more of an epic. I suggest we close this one.

**Comment by ClaudiaNicolae** [comment] 2021-11-12 13:15
Done as part of other issues

**Closed** 2021-11-12 13:15 UTC
